import esbuild from "esbuild";
import process from "node:process";
import fs from "node:fs";
import path from "node:path";
import { builtinModules } from "node:module";

const TESTVAULT_PLUGIN_DIR = process.env.LLM_WIKI_TESTVAULT
  ? path.join(process.env.LLM_WIKI_TESTVAULT, ".obsidian/plugins/llm-wiki-german")
  : null;

function syncToTestVault() {
  try {
    if (!TESTVAULT_PLUGIN_DIR || !fs.existsSync(TESTVAULT_PLUGIN_DIR)) return;
    for (const file of ["main.js", "manifest.json", "styles.css"]) {
      if (fs.existsSync(file)) {
        fs.copyFileSync(file, path.join(TESTVAULT_PLUGIN_DIR, file));
      }
    }
    console.log(`[sync] copied plugin files to TestVault`);
  } catch (err) {
    console.warn(`[sync] failed to copy to TestVault:`, err);
  }
}

const syncPlugin = {
  name: "sync-testvault",
  setup(build) {
    build.onEnd(() => {
      syncToTestVault();
    });
  },
};

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtinModules,
  ],
  platform: "node",
  format: "cjs",
  target: "es2022",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  minify: prod,
  plugins: [syncPlugin],
});

if (prod) {
  await context.rebuild();
  await context.dispose();
  process.exit(0);
} else {
  await context.watch();

  // styles.css is not an esbuild entry point, so changes to it don't trigger
  // a rebuild. Watch it separately and sync on change.
  fs.watch("styles.css", { persistent: false }, () => {
    syncToTestVault();
  });
}
